version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: api
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    ports:
    - "5432:5432"
    networks:
    - infra
    restart: unless-stopped

volumes:
  postgres:

networks:
  infra:
    driver: bridge